# Generated by Django 4.0.4 on 2022-05-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityClimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=60, verbose_name='نام شهر')),
                ('temp', models.FloatField(blank=True, null=True, verbose_name='دمای شهر')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='تاریخ اخرین بروز رسانی دما')),
            ],
        ),
    ]
